#!/bin/bash 

sudo apt-get update
sudo apt-get install bridge-utils

sudo bash -c "> /etc/network/interfaces"

echo "# interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback

auto br0
iface br0 inet static
    address 10.66.171.4
    netmask 255.255.255.0
    bridge_ports eth0 eth1
    bridge_stp off
    bridge_fd 0
    bridge_maxwait 0" | sudo tee -a /etc/network/interfaces
