#!/usr/bin/env python
"""--------------------------------------------------------------------
COPYRIGHT 2014 Stanley Innovation Inc.

Software License Agreement:

The software supplied herewith by Stanley Innovation Inc. (the "Company") 
for its licensed Segway RMP Robotic Platforms is intended and supplied to you, 
the Company's customer, for use solely and exclusively with Stanley Innovation 
products. The software is owned by the Company and/or its supplier, and is 
protected under applicable copyright laws.  All rights are reserved. Any use in 
violation of the foregoing restrictions may subject the user to criminal 
sanctions under applicable laws, as well as to civil liability for the 
breach of the terms and conditions of this license. The Company may 
immediately terminate this Agreement upon your use of the software with 
any products that are not Stanley Innovation products.

The software was written using Python programming language.  Your use 
of the software is therefore subject to the terms and conditions of the 
OSI- approved open source license viewable at http://www.python.org/.  
You are solely responsible for ensuring your compliance with the Python 
open source license.

You shall indemnify, defend and hold the Company harmless from any claims, 
demands, liabilities or expenses, including reasonable attorneys fees, incurred 
by the Company as a result of any claim or proceeding against the Company 
arising out of or based upon: 

(i) The combination, operation or use of the software by you with any hardware, 
    products, programs or data not supplied or approved in writing by the Company, 
    if such claim or proceeding would have been avoided but for such combination, 
    operation or use.
 
(ii) The modification of the software by or on behalf of you 

(iii) Your use of the software.

 THIS SOFTWARE IS PROVIDED IN AN "AS IS" CONDITION. NO WARRANTIES,
 WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 
 \file   segway_teleop.py

 \brief  Stanley Innovation enabled systems will be able to take advantage of this
         driver and the RMP stack. Only valid for a present SI release; if you have an 
         old release contact rmp@stanleyinnovation.com to get upgrade details.

 \Platform: Linux/ROS Indigo
--------------------------------------------------------------------"""
from sensor_msgs.msg import Imu
from nav_msgs.msg import Odometry
from geometry_msgs.msg import TwistStamped, PoseWithCovarianceStamped
import tf
import rospy

class SegwayExtImuCorr:
    def __init__(self):
    
        self._um7_sub = rospy.Subscriber('/um7/data',Imu,self._ext_imu_callback)
        self._odom_sub = rospy.Subscriber('/segway/feedback/wheel_odometry',Odometry,self._odometry_callback)
        self._vel_pub = rospy.Publisher('/vel', TwistStamped, queue_size=10)
        self._linear_x = 0.0
        self._vel = TwistStamped()
        self._seq = 0
        self._OdomData = Odometry()
        self._wheel_odom = Odometry()
        self._OdomPub = rospy.Publisher('/segway/odometry/local_filtered', Odometry, queue_size=10)
        rospy.Subscriber('/segway/lsm/pose', PoseWithCovarianceStamped, self._update_lsm_odom)
        
        self._OdomData.header.frame_id = '/odom'
        self._OdomData.child_frame_id  = 'base_link'
        
        
        self._OdomData.pose.covariance = [0.00017,0.0,0.0,0.0,0.0,0.0,
                                          0.0,0.00017,0.0,0.0,0.0,0.0,
                                          0.0,0.0,0.00017,0.0,0.0,0.0,
                                          0.0,0.0,0.0,0.00000,0.0,0.0,
                                          0.0,0.0,0.0,0.0,0.00000,0.0,
                                          0.0,0.0,0.0,0.0,0.0,0.00017]
             
        self._OdomData.twist.covariance = [0.00017,0.0,0.0,0.0,0.0,0.0,
                                           0.0,0.00017,0.0,0.0,0.0,0.0,
                                           0.0,0.0,0.00017,0.0,0.0,0.0,
                                           0.0,0.0,0.0,0.00000,0.0,0.0,
                                           0.0,0.0,0.0,0.0,0.00000,0.0,
                                           0.0,0.0,0.0,0.0,0.0,0.00017]
        
    def _odometry_callback(self,msg):
        self._wheel_odom = msg
        self._linear_x = msg.twist.twist.linear.x
        
    def _ext_imu_callback(self,msg):
        
        self._vel.header.stamp = msg.header.stamp 
        self._vel.header.frame_id = 'base_link'
        self._vel.header.seq = self._seq
        
        self._vel.twist.angular.z = -1.0 * msg.angular_velocity.z
        self._vel.twist.linear.x = self._linear_x
        self._vel_pub.publish(self._vel)
        self._seq+=1
        

    def _update_lsm_odom(self,msg):
        self._OdomData.header.stamp = msg.header.stamp - rospy.Duration(0.03)
        self._OdomData.header.seq += 1     
        rot = (msg.pose.pose.orientation.x, msg.pose.pose.orientation.y, msg.pose.pose.orientation.z, msg.pose.pose.orientation.w)
        pos = (msg.pose.pose.position.x,msg.pose.pose.position.y,0.0)
        
        self._OdomData.twist.twist.linear.x = self._wheel_odom.twist.twist.linear.x
        self._OdomData.twist.twist.linear.y = self._wheel_odom.twist.twist.linear.y
        self._OdomData.twist.twist.linear.z = 0.0
        self._OdomData.twist.twist.angular.x = 0.0
        self._OdomData.twist.twist.angular.y = 0.0
        self._OdomData.twist.twist.angular.z = self._vel.twist.angular.z
        self._OdomData.pose.pose = msg.pose.pose
        
        
        if not rospy.is_shutdown():
            self._OdomPub.publish(self._OdomData)        
            br = tf.TransformBroadcaster()
            br.sendTransform(pos,
                             rot,
                             rospy.get_rostime(),
                             "base_link",
                             "/odom")   
        
        

if __name__ == "__main__":
    """
    Initialize the node
    """
    rospy.init_node('segway_imu_transform')
    SegwayExtImuCorr()
    rospy.spin()
    
